PROGRAM EXAMPLE2;
VAR
    HEIGHT: INTEGER;
    WIDTH: INTEGER;
    AREA: INTEGER;
BEGIN
    HEIGHT:=5;
    WIDTH:=4;
    AREA:=HEIGHT*WIDTH;
    WRITE (AREA);
    IF AREA > 1000 THEN
        WRITE('THAT IS LARGE')
    ELSE
        WRITE('THAT IS SMALL')
END