AB123('HELLO WORLD') # 321AB
FOREVER IF INTEGER FOR  + - ;
ELSE FOR PRINT WHILE { A comment to ignore }
REAL 12.34 INT 234
STRING VAR { comment } OR :
'I AM A STRING, I AM ALSO A STRING'
'' 12. 34 AREALLYLONGNAME IFFINESS

